id = "cosense"
name = "Cosense"
version = "0.1.0"
schema_version = 1
description = ".csn と .csnx の記法に色を付ける。"
repository = "https://github.com/qaynam/cosense-toolbox"

languages = ["languages/csn", "languages/csnx"]

[language_servers.csn-lsp]
name = "Cosense Language Server"
languages = ["Cosense", "Cosense X"]
