import { parse } from "@cosense-toolbox/parser";
import { toHtml } from "@cosense-toolbox/parser/compile";

const source = [
  "その他の書き方",
  "基本的な[ブラケティング]の他にも、色々な[記法]があります",
  "",
  "外部リンク (一般のWebページへのリンク)",
  " URLを書くとリンクになる",
  "  https://yahoo.co.jp",
  "	`[URL タイトル]`",
  "	 [https://yahoo.com Yahoo!]",
  " `[タイトル URL]`逆順でもok",
  "  [Yahoo! https://yahoo.com]",
  "",
  "画像",
  "	`[画像URL]`",
  "  [https://i.gyazo.com/da78df293f9e83a74b5402411e2f2e01.png]",
  " `[[画像URL]]`",
  "  横幅いっぱい、高さ制限無しで大きな画像を表示",
  "",
  "リンク付き画像",
  "	`[リンク先URL 画像URL]`",
  "  [http://yahoo.co.jp https://i.gyazo.com/da78df293f9e83a74b5402411e2f2e01.png]",
  "",
  "別プロジェクトへのリンク",
  " `/プロジェクト名/ページ名`",
  " [/icons]",
  " [/icons/すごい]",
  "",
  "アイコン",
  " [rakusai.icon]",
  " [/icons/炎上.icon]",
  "",
  "[数式]",
  " [$ \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}]",
  "",
  "[HashTag]",
  " #HashTag",
  "",
  "引用",
  " > 行頭に`>`を書くと引用になります",
  "",
  "コード",
  " バッククオート`\\``で囲む",
  "  `function() {  return \\`hello\\` }`",
  "",
  "[コードブロック]",
  " code:hello.js",
  "  function () {",
  "    alert(document.location.href)",
  '    console.log("hello")',
  "    // コメントも書けるぞ",
  "  }",
  "",
  "[テーブル]",
  " `table:テーブル名` の後、インデントしてtab区切り",
  " table:テーブルの例",
  "  abc	def",
  "  12345	6789",
  "  長い長い文字列	短い文字列",
  "",
  "コマンドライン",
  " 行頭に`$`もしくは`%`",
  " $ git reset --hard HEAD^",
  " % cp a.txt b.txt",
  "",
  "[[強調]]と[*** 大きな文字]",
  "	`[[強調]]` ⇒ [[強調]]",
  " `[* 強調]` ⇒ [* 強調]",
  " `[**** もっと大きな文字]` => [**** もっと大きな文字]",
  "",
  "[/ 斜体]",
  " `[/ 斜体文字]` ⇒ [/ 斜体文字]",
  " `[/* 太字斜体文字]` => [/* 太字斜体文字]",
  "",
  "[- 打ち消し線]",
  " `[- 打ち消し]` ⇒ [- 打ち消し]",
].join("\n");

export const html = toHtml(parse(source));
